#ifndef PRJMYGUILIBRARY_GLOBAL_H
#define PRJMYGUILIBRARY_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(PRJMYGUILIBRARY_LIBRARY)
#  define PRJMYGUILIBRARYSHARED_EXPORT Q_DECL_EXPORT
#else
#  define PRJMYGUILIBRARYSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // PRJMYGUILIBRARY_GLOBAL_H
